name: mujoco-sim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - quaternion
  - pip
  - pip:
      - mujoco>=3.1.0
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - torch==2.10.0+cu130
      - torchvision==0.25.0+cu130
      - torchaudio==2.10.0+cu130
      - pyyaml>=6.0
      - mujoco-python-viewer>=0.1.4  # 用于渲染无头服务器或桌面端的 3D 画面
      - stable-baselines3[extra]>=2.2.1  # 强化学习核心算法库 (含 tensorboard)
